/** Central route paths for Expo Router */
export const Routes = {
  splash: "/splash",
  welcome: "/(auth)/welcome",
  login: "/(auth)/login",
  createAccount: "/(auth)/create-account",
  signupParent: "/(auth)/signup/parent",
  signupOrthophonist: "/(auth)/signup/orthophonist",
  tabs: "/(tabs)",
  settings: "/(tabs)/settings",
  lettersGame: "/letters-game",
  videoQuestionsGame: "/questions-game",
  questionsPlacesGame: "/questions-game/places",
  questionsSizesGame: "/questions-game/sizes",
  questionsColorsGame: "/questions-game/colors",
  questionsInteractiveGame: "/questions-game/interactive",
  balloonGame: "/balloon-game",
  candlesGame: "/candles-game",
  tasks: "/tasks",
  history: "/history",
  accomplishments: "/accomplishments",
} as const;